### ISSUE TITLE
I can not access the Internet when I turn off and turn on the router

### ISSUE THREAD

**Issue by liveonloan** [basil00/reqrypt#12]
If you turn off and turn on the router, when reqrypt works, Internet access is lost.
It is necessary to restart reqrypt manually - then all is well.
The same problem if there was a breakage of communication through the fault of the provider.
You must restart reqrypt manually.

These settings are used: http://funkyimg.com/i/2BzXb.jpg

**Comment by basil00** [comment]
This part of ReQrypt could be improved.  Ideally, ReQrypt should try to reconnect if it appears a given tunnel has gone down (or if they all go down).  I'll take this as a feature request.

Actually, there is already some logic in the client for detecting unreliable/down tunnels.  However, currently it just attempts to "deprioritize" the tunnel rather than reconnect.

**Comment by liveonloan** [comment]
Thank you!

**Comment by basil00** [comment]
I guess this was related to #13.

**Comment by liveonloan** [comment]
@basil00 Hello!
After rebooting the router, it is necessary to restart ReQrypt.
Otherwise, the Internet does not work.
Perhaps this is the features of my router ... I do not know for sure.
Here's a video: http://www8.zippyshare.com/v/SaxQHDGU/file.html
I hope this helps you understand.

I'll probably buy a new router.
Keenetic Giga KN-1010 I think it will work fine.

**Comment by WPMGPRoSToTeMa** [comment]
I have old Keenetic Giga and there is the same problem with rebooting.
