### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by odkrys** [basil00/reqrypt#33]
in armv8 aarch64. gcc (OpenWrt GCC 6.3.0) 6.3.0

1st error. (maes)
https://pastebin.com/XsUwQ3Xp

2nd error. (after removing maes flag in cfg.mk)
https://pastebin.com/pkm72eGn

3rd error. (afte removing encodings/aes_hardware.o \ line in src/Makefile)
https://pastebin.com/VkwuTJRu
http_data.c and install_data.c files size increased infinitely (xGbyte) and compilation never end.

**Comment by basil00** [comment]
The 1st and 2nd error are to be expected, since ReQrypt is using x86-specific AES instruction set extensions.  There is a non-hardware alternative implementation (`encodings/aes.c`) that should work for ARM.

The last error seems like a bug in `file2c` for ARM?  Hard to diagnose since I do not have access to that architecture.
